function [ValoresMC8, VolMC8,StepMC,ValoresHeston8,...
    VolHeston8,StepHeston] = HSMCVolImp(Spot,r,q,...
        Tiempo,Strike,MC8,Heston8,SigmaMCBS...
        ,Accuracy,e)
%Funcion que oculta codigo, calcula lo necesario para realizar
%posteriormente la comparacion con los pasos anteriormente propuestos.
%   Calcula la volatilidad implicita para su posterior comparacion en el
%   pilar ATM para el tenor de 3 meses.
for k=1:size(r,1)
    [ValoresMC8(k,1), VolMC8(k,1),StepMC(k,1)]=VolBS2(Spot(k,1),r(k,2)...
        ,q(k,2),Tiempo(k,2),Strike(k,8),MC8(k,1),SigmaMCBS...
        ,Accuracy,e); %#ok<AGROW>
end
for k=1:size(r,1)
    [ValoresHeston8(k,1), VolHeston8(k,1),StepHeston(k,1)]=...
        VolBS2(Spot(k,1),r(k,2),q(k,2),...
        Tiempo(k,2),Strike(k,8),Heston8(k,1),SigmaMCBS...
        ,Accuracy,e); %#ok<AGROW>
end
end

